let collegeName="CDC Deemed to University";
console.log(collegeName);
let collegeN=new String("CDC college");
console.log(collegeN);
console.log(collegeName.length);
console.log(collegeName.toLowerCase());
console.log(collegeName.toUpperCase());
console.log(collegeName.charAt('2'));
console.log(collegeName.startsWith ('cdc'));
console.log(collegeName.startsWith ('CDC'));
console.log(collegeName.endsWith ('university'));
console.log(collegeName.endsWith ('University'));
console.log(collegeName.includes ('Deemed'));
console.log(collegeName.includes ('DEEMED'));
console.log(collegeName.repeat ('3'));
console.log(`hii ${collegeName}`);
